#!/bin/bash
# doc-extractor.sh — 从 .sh 文件提取 API 文档
# v3.5.0 新增
# 用法: bash scripts/doc-extractor.sh [output_file]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLOW_KIT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT="${1:-$FLOW_KIT_DIR/API-REFERENCE.md}"

echo "# API Reference" > "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Auto-generated by doc-extractor.sh" >> "$OUTPUT"
echo "" >> "$OUTPUT"

extract_from_dir() {
    local dir="$1"
    local title="$2"
    echo "## $title" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    for script in "$dir"/*.sh; do
        [ -f "$script" ] || continue
        local basename
        basename=$(basename "$script")
        echo "### $basename" >> "$OUTPUT"
        echo "" >> "$OUTPUT"

        local in_fn=false fn_name=""
        while IFS= read -r line; do
            # 函数定义
            if [[ "$line" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)\(\) ]]; then
                if [ -n "$fn_name" ]; then
                    echo "" >> "$OUTPUT"
                fi
                fn_name="${BASH_REMATCH[1]}"
                echo "- \`$fn_name()\`" >> "$OUTPUT"
                in_fn=true
                continue
            fi
            # 函数上方注释
            if $in_fn && [[ "$line" =~ ^#\ (.*) ]]; then
                echo "  ${BASH_REMATCH[1]}" >> "$OUTPUT"
            elif [[ ! "$line" =~ ^# ]]; then
                if $in_fn && [ -n "$fn_name" ]; then
                    echo "" >> "$OUTPUT"
                fi
                in_fn=false
                fn_name=""
            fi
        done < "$script"
        echo "" >> "$OUTPUT"
    done
}

extract_from_dir "$FLOW_KIT_DIR/lib" "Library (lib/)"
extract_from_dir "$FLOW_KIT_DIR/scripts" "Scripts (scripts/)"

echo "Generated: $OUTPUT"
